// Each theme maps CSS custom property names to their values.
// These override the @theme defaults in index.css at runtime.

export interface ThemeDefinition {
  id: string;
  name: string;
  /** The representative swatch color shown in the picker */
  swatch: string;
  /** Emoji icon for the theme */
  icon: string;
  vars: Record<string, string>;
}

export const themes: ThemeDefinition[] = [
  {
    id: "indigo",
    name: "Indigo Night",
    swatch: "#2D1B69",
    icon: "🔮",
    vars: {
      "--color-surface-tint": "#6750A4",
      "--color-on-primary-container": "#D4BBFF",
      "--color-on-tertiary-fixed": "#31111D",
      "--color-secondary": "#625B71",
      "--color-outline": "#79747E",
      "--color-primary-fixed": "#EADDFF",
      "--color-on-secondary-fixed": "#1D192B",
      "--color-primary-fixed-dim": "#D0BCFF",
      "--color-on-background": "#1C1B1F",
      "--color-on-secondary-container": "#6B6580",
      "--color-primary": "#2D1B69",
      "--color-surface": "#FFFBFE",
      "--color-secondary-fixed": "#E8DEF8",
      "--color-surface-container-low": "#F7F2FA",
      "--color-surface-container": "#F3EDF7",
      "--color-on-tertiary-fixed-variant": "#633B48",
      "--color-surface-variant": "#E7E0EC",
      "--color-on-primary-fixed": "#21005E",
      "--color-secondary-container": "#E8DEF8",
      "--color-surface-bright": "#FFFBFE",
      "--color-on-surface": "#1C1B1F",
      "--color-tertiary": "#7D5260",
      "--color-surface-container-lowest": "#ffffff",
      "--color-tertiary-container": "#986977",
      "--color-surface-dim": "#DED8E1",
      "--color-on-tertiary-container": "#FFD8E4",
      "--color-tertiary-fixed-dim": "#EFB8C8",
      "--color-outline-variant": "#CAC4D0",
      "--color-on-primary": "#ffffff",
      "--color-inverse-primary": "#D0BCFF",
      "--color-tertiary-fixed": "#FFD8E4",
      "--color-on-secondary-fixed-variant": "#4A4458",
      "--color-inverse-surface": "#313033",
      "--color-on-surface-variant": "#49454F",
      "--color-background": "#FFFBFE",
      "--color-surface-container-highest": "#E6E0E9",
      "--color-surface-container-high": "#ECE6F0",
      "--color-primary-container": "#3F2D80",
      "--color-secondary-fixed-dim": "#CCC2DC",
      "--color-on-secondary": "#ffffff",
      "--color-inverse-on-surface": "#F4EFF4",
      "--color-on-primary-fixed-variant": "#381E72",
    },
  },
  {
    id: "ocean",
    name: "Ocean Teal",
    swatch: "#006A6A",
    icon: "🌊",
    vars: {
      "--color-surface-tint": "#006A6A",
      "--color-on-primary-container": "#6FF7F6",
      "--color-on-tertiary-fixed": "#001F3D",
      "--color-secondary": "#4A6363",
      "--color-outline": "#6F7979",
      "--color-primary-fixed": "#6FF7F6",
      "--color-on-secondary-fixed": "#051F1F",
      "--color-primary-fixed-dim": "#4FDBDA",
      "--color-on-background": "#191C1C",
      "--color-on-secondary-container": "#506464",
      "--color-primary": "#006A6A",
      "--color-surface": "#F8FAFA",
      "--color-secondary-fixed": "#CCE8E7",
      "--color-surface-container-low": "#F2F4F4",
      "--color-surface-container": "#ECF0EF",
      "--color-on-tertiary-fixed-variant": "#004880",
      "--color-surface-variant": "#DAE5E4",
      "--color-on-primary-fixed": "#002020",
      "--color-secondary-container": "#CCE8E7",
      "--color-surface-bright": "#F8FAFA",
      "--color-on-surface": "#191C1C",
      "--color-tertiary": "#3B6090",
      "--color-surface-container-lowest": "#ffffff",
      "--color-tertiary-container": "#4A72A2",
      "--color-surface-dim": "#D8DADA",
      "--color-on-tertiary-container": "#D4E3FF",
      "--color-tertiary-fixed-dim": "#A9C7FA",
      "--color-outline-variant": "#BEC9C8",
      "--color-on-primary": "#ffffff",
      "--color-inverse-primary": "#4FDBDA",
      "--color-tertiary-fixed": "#D4E3FF",
      "--color-on-secondary-fixed-variant": "#324B4B",
      "--color-inverse-surface": "#2D3131",
      "--color-on-surface-variant": "#3F4948",
      "--color-background": "#F8FAFA",
      "--color-surface-container-highest": "#E1E3E3",
      "--color-surface-container-high": "#E6E9E8",
      "--color-primary-container": "#008584",
      "--color-secondary-fixed-dim": "#B0CCCB",
      "--color-on-secondary": "#ffffff",
      "--color-inverse-on-surface": "#EFF1F1",
      "--color-on-primary-fixed-variant": "#004F50",
    },
  },
  {
    id: "rose",
    name: "Warm Rose",
    swatch: "#8C1D5B",
    icon: "🌹",
    vars: {
      "--color-surface-tint": "#A03172",
      "--color-on-primary-container": "#FFD8E8",
      "--color-on-tertiary-fixed": "#1B1006",
      "--color-secondary": "#6E5868",
      "--color-outline": "#7F747A",
      "--color-primary-fixed": "#FFD8E8",
      "--color-on-secondary-fixed": "#271624",
      "--color-primary-fixed-dim": "#F5B0D5",
      "--color-on-background": "#201A1E",
      "--color-on-secondary-container": "#7A6374",
      "--color-primary": "#8C1D5B",
      "--color-surface": "#FFF8F9",
      "--color-secondary-fixed": "#F8D8EF",
      "--color-surface-container-low": "#FCF0F5",
      "--color-surface-container": "#F6EBF0",
      "--color-on-tertiary-fixed-variant": "#5A4319",
      "--color-surface-variant": "#F0DEE6",
      "--color-on-primary-fixed": "#3A0025",
      "--color-secondary-container": "#F8D8EF",
      "--color-surface-bright": "#FFF8F9",
      "--color-on-surface": "#201A1E",
      "--color-tertiary": "#765A2D",
      "--color-surface-container-lowest": "#ffffff",
      "--color-tertiary-container": "#8F7142",
      "--color-surface-dim": "#E3D7DD",
      "--color-on-tertiary-container": "#FFDEAA",
      "--color-tertiary-fixed-dim": "#E6C288",
      "--color-outline-variant": "#D3C1CA",
      "--color-on-primary": "#ffffff",
      "--color-inverse-primary": "#F5B0D5",
      "--color-tertiary-fixed": "#FFDEAA",
      "--color-on-secondary-fixed-variant": "#554050",
      "--color-inverse-surface": "#362E33",
      "--color-on-surface-variant": "#504349",
      "--color-background": "#FFF8F9",
      "--color-surface-container-highest": "#ECE0E5",
      "--color-surface-container-high": "#F1E5EB",
      "--color-primary-container": "#AD3B80",
      "--color-secondary-fixed-dim": "#DBBDD3",
      "--color-on-secondary": "#ffffff",
      "--color-inverse-on-surface": "#F9ECF2",
      "--color-on-primary-fixed-variant": "#6E0D4A",
    },
  },
  {
    id: "sapphire",
    name: "Sapphire Blue",
    swatch: "#0B57D0",
    icon: "💎",
    vars: {
      "--color-surface-tint": "#0B57D0",
      "--color-on-primary-container": "#D3E3FD",
      "--color-on-tertiary-fixed": "#1E1A00",
      "--color-secondary": "#565E71",
      "--color-outline": "#74777F",
      "--color-primary-fixed": "#D3E3FD",
      "--color-on-secondary-fixed": "#131C2C",
      "--color-primary-fixed-dim": "#A8C7FA",
      "--color-on-background": "#1B1B1F",
      "--color-on-secondary-container": "#5E6678",
      "--color-primary": "#0B57D0",
      "--color-surface": "#FAFBFF",
      "--color-secondary-fixed": "#DAE2F9",
      "--color-surface-container-low": "#F3F3FA",
      "--color-surface-container": "#EEEEF5",
      "--color-on-tertiary-fixed-variant": "#524600",
      "--color-surface-variant": "#E0E2EC",
      "--color-on-primary-fixed": "#001A44",
      "--color-secondary-container": "#DAE2F9",
      "--color-surface-bright": "#FAFBFF",
      "--color-on-surface": "#1B1B1F",
      "--color-tertiary": "#6D5E0F",
      "--color-surface-container-lowest": "#ffffff",
      "--color-tertiary-container": "#887625",
      "--color-surface-dim": "#DADAE0",
      "--color-on-tertiary-container": "#FBE365",
      "--color-tertiary-fixed-dim": "#D8C84D",
      "--color-outline-variant": "#C4C6D0",
      "--color-on-primary": "#ffffff",
      "--color-inverse-primary": "#A8C7FA",
      "--color-tertiary-fixed": "#FBE365",
      "--color-on-secondary-fixed-variant": "#3E4759",
      "--color-inverse-surface": "#303036",
      "--color-on-surface-variant": "#44474F",
      "--color-background": "#FAFBFF",
      "--color-surface-container-highest": "#E3E2E6",
      "--color-surface-container-high": "#E8E8EE",
      "--color-primary-container": "#1B6EF3",
      "--color-secondary-fixed-dim": "#BEC6DC",
      "--color-on-secondary": "#ffffff",
      "--color-inverse-on-surface": "#F1F0F4",
      "--color-on-primary-fixed-variant": "#084298",
    },
  },
  {
    id: "amber",
    name: "Amber Gold",
    swatch: "#7C5800",
    icon: "✨",
    vars: {
      "--color-surface-tint": "#7C5800",
      "--color-on-primary-container": "#FFDEA2",
      "--color-on-tertiary-fixed": "#00201E",
      "--color-secondary": "#6D5D3F",
      "--color-outline": "#7E7667",
      "--color-primary-fixed": "#FFDEA2",
      "--color-on-secondary-fixed": "#251A04",
      "--color-primary-fixed-dim": "#F0BF48",
      "--color-on-background": "#1E1B16",
      "--color-on-secondary-container": "#796A4A",
      "--color-primary": "#7C5800",
      "--color-surface": "#FFF8F0",
      "--color-secondary-fixed": "#F8E0C2",
      "--color-surface-container-low": "#F8F2EB",
      "--color-surface-container": "#F3ECE5",
      "--color-on-tertiary-fixed-variant": "#144F4B",
      "--color-surface-variant": "#ECE1CF",
      "--color-on-primary-fixed": "#271900",
      "--color-secondary-container": "#F8E0C2",
      "--color-surface-bright": "#FFF8F0",
      "--color-on-surface": "#1E1B16",
      "--color-tertiary": "#316763",
      "--color-surface-container-lowest": "#ffffff",
      "--color-tertiary-container": "#3E7F7A",
      "--color-surface-dim": "#E0D9D1",
      "--color-on-tertiary-container": "#B5EDE7",
      "--color-tertiary-fixed-dim": "#9AD1CB",
      "--color-outline-variant": "#CFC5B4",
      "--color-on-primary": "#ffffff",
      "--color-inverse-primary": "#F0BF48",
      "--color-tertiary-fixed": "#B5EDE7",
      "--color-on-secondary-fixed-variant": "#544529",
      "--color-inverse-surface": "#34302A",
      "--color-on-surface-variant": "#4D4639",
      "--color-background": "#FFF8F0",
      "--color-surface-container-highest": "#E8E1D9",
      "--color-surface-container-high": "#EDE7E0",
      "--color-primary-container": "#9A7000",
      "--color-secondary-fixed-dim": "#DBC5A6",
      "--color-on-secondary": "#ffffff",
      "--color-inverse-on-surface": "#F7F0E8",
      "--color-on-primary-fixed-variant": "#5E4200",
    },
  },
  {
    id: "slate",
    name: "Midnight Slate",
    swatch: "#3C4043",
    icon: "🌑",
    vars: {
      "--color-surface-tint": "#5C6BC0",
      "--color-on-primary-container": "#C5CAE9",
      "--color-on-tertiary-fixed": "#1A1100",
      "--color-secondary": "#5F6368",
      "--color-outline": "#747775",
      "--color-primary-fixed": "#C5CAE9",
      "--color-on-secondary-fixed": "#1A1C1E",
      "--color-primary-fixed-dim": "#9FA8DA",
      "--color-on-background": "#1F1F1F",
      "--color-on-secondary-container": "#6A6D72",
      "--color-primary": "#3C4043",
      "--color-surface": "#FAFAFA",
      "--color-secondary-fixed": "#E0E2E6",
      "--color-surface-container-low": "#F4F4F4",
      "--color-surface-container": "#EEEEEE",
      "--color-on-tertiary-fixed-variant": "#5A4500",
      "--color-surface-variant": "#E0E0E0",
      "--color-on-primary-fixed": "#1A1B2E",
      "--color-secondary-container": "#E0E2E6",
      "--color-surface-bright": "#FAFAFA",
      "--color-on-surface": "#1F1F1F",
      "--color-tertiary": "#795B00",
      "--color-surface-container-lowest": "#ffffff",
      "--color-tertiary-container": "#947100",
      "--color-surface-dim": "#DADADA",
      "--color-on-tertiary-container": "#FFE082",
      "--color-tertiary-fixed-dim": "#FFCA28",
      "--color-outline-variant": "#C4C4C4",
      "--color-on-primary": "#ffffff",
      "--color-inverse-primary": "#9FA8DA",
      "--color-tertiary-fixed": "#FFE082",
      "--color-on-secondary-fixed-variant": "#444749",
      "--color-inverse-surface": "#303030",
      "--color-on-surface-variant": "#444746",
      "--color-background": "#FAFAFA",
      "--color-surface-container-highest": "#E0E0E0",
      "--color-surface-container-high": "#E8E8E8",
      "--color-primary-container": "#525760",
      "--color-secondary-fixed-dim": "#C4C6CA",
      "--color-on-secondary": "#ffffff",
      "--color-inverse-on-surface": "#F0F0F0",
      "--color-on-primary-fixed-variant": "#303348",
    },
  },
];

export const DEFAULT_THEME_ID = "indigo";

export function getThemeById(id: string): ThemeDefinition {
  return themes.find((t) => t.id === id) ?? themes[0];
}
