// Each theme maps CSS custom property names to their values.
// These override the @theme defaults in index.css at runtime.

export interface ThemeDefinition {
  id: string;
  name: string;
  /** The representative swatch color shown in the picker */
  swatch: string;
  vars: Record<string, string>;
}

const legacyThemes: ThemeDefinition[] = [
  {
    id: "ocean",
    name: "Ocean Teal",
    swatch: "#006A6A",
    vars: {
      "--color-surface-tint": "#006A6A",
      "--color-on-primary-container": "#6FF7F6",
      "--color-on-tertiary-fixed": "#001F3D",
      "--color-secondary": "#4A6363",
      "--color-outline": "#6F7979",
      "--color-primary-fixed": "#6FF7F6",
      "--color-on-secondary-fixed": "#051F1F",
      "--color-primary-fixed-dim": "#4FDBDA",
      "--color-on-background": "#191C1C",
      "--color-on-secondary-container": "#506464",
      "--color-primary": "#006A6A",
      "--color-surface": "#F8FAFA",
      "--color-secondary-fixed": "#CCE8E7",
      "--color-surface-container-low": "#F2F4F4",
      "--color-surface-container": "#ECF0EF",
      "--color-on-tertiary-fixed-variant": "#004880",
      "--color-surface-variant": "#DAE5E4",
      "--color-on-primary-fixed": "#002020",
      "--color-secondary-container": "#CCE8E7",
      "--color-surface-bright": "#F8FAFA",
      "--color-on-surface": "#191C1C",
      "--color-tertiary": "#3B6090",
      "--color-surface-container-lowest": "#ffffff",
      "--color-tertiary-container": "#4A72A2",
      "--color-surface-dim": "#D8DADA",
      "--color-on-tertiary-container": "#D4E3FF",
      "--color-tertiary-fixed-dim": "#A9C7FA",
      "--color-outline-variant": "#BEC9C8",
      "--color-on-primary": "#ffffff",
      "--color-inverse-primary": "#4FDBDA",
      "--color-tertiary-fixed": "#D4E3FF",
      "--color-on-secondary-fixed-variant": "#324B4B",
      "--color-inverse-surface": "#2D3131",
      "--color-on-surface-variant": "#3F4948",
      "--color-background": "#F8FAFA",
      "--color-surface-container-highest": "#E1E3E3",
      "--color-surface-container-high": "#E6E9E8",
      "--color-primary-container": "#008584",
      "--color-secondary-fixed-dim": "#B0CCCB",
      "--color-on-secondary": "#ffffff",
      "--color-inverse-on-surface": "#EFF1F1",
      "--color-on-primary-fixed-variant": "#004F50",
    },
  },

  {
    id: "slate",
    name: "Midnight Slate",
    swatch: "#3C4043",
    vars: {
      "--color-surface-tint": "#5C6BC0",
      "--color-on-primary-container": "#C5CAE9",
      "--color-on-tertiary-fixed": "#1A1100",
      "--color-secondary": "#5F6368",
      "--color-outline": "#747775",
      "--color-primary-fixed": "#C5CAE9",
      "--color-on-secondary-fixed": "#1A1C1E",
      "--color-primary-fixed-dim": "#9FA8DA",
      "--color-on-background": "#1F1F1F",
      "--color-on-secondary-container": "#6A6D72",
      "--color-primary": "#3C4043",
      "--color-surface": "#FAFAFA",
      "--color-secondary-fixed": "#E0E2E6",
      "--color-surface-container-low": "#F4F4F4",
      "--color-surface-container": "#EEEEEE",
      "--color-on-tertiary-fixed-variant": "#5A4500",
      "--color-surface-variant": "#E0E0E0",
      "--color-on-primary-fixed": "#1A1B2E",
      "--color-secondary-container": "#E0E2E6",
      "--color-surface-bright": "#FAFAFA",
      "--color-on-surface": "#1F1F1F",
      "--color-tertiary": "#795B00",
      "--color-surface-container-lowest": "#ffffff",
      "--color-tertiary-container": "#947100",
      "--color-surface-dim": "#DADADA",
      "--color-on-tertiary-container": "#FFE082",
      "--color-tertiary-fixed-dim": "#FFCA28",
      "--color-outline-variant": "#C4C4C4",
      "--color-on-primary": "#ffffff",
      "--color-inverse-primary": "#9FA8DA",
      "--color-tertiary-fixed": "#FFE082",
      "--color-on-secondary-fixed-variant": "#444749",
      "--color-inverse-surface": "#303030",
      "--color-on-surface-variant": "#444746",
      "--color-background": "#FAFAFA",
      "--color-surface-container-highest": "#E0E0E0",
      "--color-surface-container-high": "#E8E8E8",
      "--color-primary-container": "#525760",
      "--color-secondary-fixed-dim": "#C4C6CA",
      "--color-on-secondary": "#ffffff",
      "--color-inverse-on-surface": "#F0F0F0",
      "--color-on-primary-fixed-variant": "#303348",
    },
  },
  {
    id: "meadow",
    name: "Meadow Light",
    swatch: "#286A42",
    vars: {
      "--color-surface": "#F7FBF6",
      "--color-background": "#F7FBF6",
      "--color-surface-bright": "#F7FBF6",
      "--color-surface-container-lowest": "#FFFFFF",
      "--color-surface-container-low": "#EFF7ED",
      "--color-surface-container": "#E8F1E5",
      "--color-surface-container-high": "#E2EBDF",
      "--color-surface-container-highest": "#DCE5D9",
      "--color-surface-variant": "#DCE8D9",
      "--color-surface-dim": "#D5DED2",
      "--color-on-surface": "#182019",
      "--color-on-background": "#182019",
      "--color-on-surface-variant": "#435044",
      "--color-outline": "#738174",
      "--color-outline-variant": "#C2D0C0",
      "--color-primary": "#286A42",
      "--color-primary-container": "#A8F5B9",
      "--color-on-primary": "#FFFFFF",
      "--color-on-primary-container": "#005225",
      "--color-secondary": "#526350",
      "--color-secondary-container": "#D5E8D0",
      "--color-on-secondary": "#FFFFFF",
      "--color-tertiary": "#59621B",
      "--color-tertiary-container": "#DCE58C",
      "--color-on-tertiary-container": "#414900",
      "--color-surface-tint": "#286A42",
      "--color-inverse-surface": "#2D332D",
      "--color-inverse-on-surface": "#EDF5EA",
      "--color-inverse-primary": "#8BD89E",
    },
  },
  {
    id: "obsidian",
    name: "Obsidian Dark",
    swatch: "#67D7E8",
    vars: {
      "--color-surface": "#171D23",
      "--color-background": "#0D1117",
      "--color-surface-bright": "#343D47",
      "--color-surface-container-lowest": "#080B0F",
      "--color-primary-fixed": "#f6f8ff",
      "--color-surface-container-low": "#121820",
      "--color-surface-container": "#1D252E",
      "--color-surface-container-high": "#27313B",
      "--color-surface-container-highest": "#343D47",
      "--color-surface-variant": "#3D4A55",
      "--color-surface-dim": "#0D1117",
      "--color-on-surface": "#DEE7ED",
      "--color-on-background": "#DEE7ED",
      "--color-on-surface-variant": "#B9C6CE",
      "--color-outline": "#8797A2",
      "--color-outline-variant": "#3D4A55",
      "--color-primary": "#67D7E8",
      "--color-primary-container": "#075968",
      "--color-on-primary": "#00363E",
      "--color-on-primary-container": "#A8EEFA",
      "--color-secondary": "#B8CBD0",
      "--color-secondary-container": "#30464B",
      "--color-on-secondary": "#1A3035",
      "--color-tertiary": "#E8B86A",
      "--color-tertiary-container": "#5B4318",
      "--color-on-tertiary-container": "#FFDEA6",
      "--color-surface-tint": "#67D7E8",
      "--color-inverse-surface": "#DEE7ED",
      "--color-inverse-on-surface": "#273238",
      "--color-inverse-primary": "#006876",
    },
  },
];

export const themes: ThemeDefinition[] = [...legacyThemes];

export const DEFAULT_THEME_ID = "slate";

export function getThemeById(id: string): ThemeDefinition {
  return themes.find((t) => t.id === id) ?? themes[0];
}
